name: friendzone

services:
  api:
    build: ../backend
    container_name: friendzone-api
    restart: always
    ports:
      - 3010:3000
    env_file:
      - ./api.env
    depends_on:
      - mongodb
    networks:
      - friendzone_network

  app:
    build: ../frontend
    container_name: friendzone-app
    restart: always
    ports:
      - 3000:3000
    environment:
      VITE_APPLICATION_NAME: "Friendzone"
    env_file:
      - ./app.env
    depends_on:
      - api
    networks:
      - friendzone_network

  mongodb:
    image: mongo:8-noble
    container_name: friendzone-mongodb
    restart: always
    ports:
      - 5030:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: friendzone123
    volumes:
      - friendzone_mongodb_mnt:/data/db
    command: ["mongod", "--bind_ip_all"]
    healthcheck:
      test:
        - CMD
        - mongosh
        - 'mongodb://localhost:5030/admin'
        - '--eval=db.runCommand({ping:1})'
      retries: 3
      timeout: 5s
    networks:
      - friendzone_network

  mongodb-client:
    image: mongo-express:latest
    container_name: friendzone-mongodb-client
    restart: unless-stopped
    ports:
      - 5050:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: friendzone123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: fz123
      ME_CONFIG_MONGODB_URL: mongodb://root:friendzone123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - friendzone_network

volumes:
  friendzone_mongodb_mnt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mongodb
  friendzone_redis_mnt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis

networks:
  friendzone_network:
    driver: bridge