events {
}

http {
    server {
        listen 80;
        listen [::]:80;

        server_name friendzone.gmorikawa.dev www.friendzone.gmorikawa.dev;
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://friendzone.gmorikawa.dev$request_uri;
        }
    }

    server {
        listen 80;
        listen [::]:80;

        server_name friendzone-api.gmorikawa.dev www.friendzone-api.gmorikawa.dev;
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://friendzone-api.gmorikawa.dev$request_uri;
        }
    }

    # server {
    #     listen 443 default_server ssl;
    #     listen [::]:443 ssl;

    #     server_name friendzone.gmorikawa.dev www.friendzone.gmorikawa.dev;

    #     ssl_certificate /etc/nginx/ssl/live/friendzone.gmorikawa.dev/fullchain.pem;
    #     ssl_certificate_key /etc/nginx/ssl/live/friendzone.gmorikawa.dev/privkey.pem;
        
    #     location / {
    #         proxy_pass http://app:3000;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "upgrade";
    #     }
    # }

    # server {
    #     listen 443 ssl;
    #     listen [::]:443 ssl;

    #     server_name friendzone-api.gmorikawa.dev www.friendzone-api.gmorikawa.dev;

    #     ssl_certificate /etc/nginx/ssl/live/friendzone-api.gmorikawa.dev/fullchain.pem;
    #     ssl_certificate_key /etc/nginx/ssl/live/friendzone-api.gmorikawa.dev/privkey.pem;
        
    #     location / {
    #         proxy_pass http://api:3000;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #     }
    # }
}
